// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchaerbeekMunicipality.Infrastructure.Persistence;

#nullable disable

namespace SchaerbeekMunicipality.Infrastructure.Migrations
{
    [DbContext(typeof(MunicipalDbContext))]
    [Migration("20260705174146_CertificatesAndNotifications")]
    partial class CertificatesAndNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchaerbeekMunicipality.Domain.Certificates.CertificateRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CertificateType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("certificate_type");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("IssuedByOfficerId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_officer_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference_number");

                    b.Property<Guid>("RegistrationCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_case_id");

                    b.HasKey("Id")
                        .HasName("pk_certificate_requests");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_certificate_requests_reference_number");

                    b.HasIndex("RegistrationCaseId")
                        .HasDatabaseName("ix_certificate_requests_registration_case_id");

                    b.ToTable("certificate_requests", (string)null);
                });

            modelBuilder.Entity("SchaerbeekMunicipality.Domain.Documents.AdministrativeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_hash");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("RegistrationCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_case_id");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByOfficerId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_officer_id");

                    b.HasKey("Id")
                        .HasName("pk_administrative_documents");

                    b.HasIndex("RegistrationCaseId")
                        .HasDatabaseName("ix_administrative_documents_registration_case_id");

                    b.ToTable("administrative_documents", (string)null);
                });

            modelBuilder.Entity("SchaerbeekMunicipality.Domain.Household.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RegistrationCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_case_id");

                    b.HasKey("Id")
                        .HasName("pk_households");

                    b.HasIndex("RegistrationCaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_households_registration_case_id");

                    b.ToTable("households", (string)null);
                });

            modelBuilder.Entity("SchaerbeekMunicipality.Domain.Household.HouseholdMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("given_name");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_household_members");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_household_members_household_id");

                    b.ToTable("household_members", (string)null);
                });

            modelBuilder.Entity("SchaerbeekMunicipality.Domain.Identity.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("BisNumber")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("bis_number");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("given_name");

                    b.Property<Guid?>("LinkedRegisterRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_register_record_id");

                    b.Property<string>("NationalRegisterNumber")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("national_register_number");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("nationality");

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.HasIndex("LinkedRegisterRecordId")
                        .HasDatabaseName("ix_persons_linked_register_record_id");

                    b.HasIndex("NationalRegisterNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_persons_national_register_number");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("SchaerbeekMunicipality.Domain.Immigration.ResidencePermit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("card_number");

                    b.Property<string>("IssuingAuthority")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("issuing_authority");

                    b.Property<string>("PermitType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permit_type");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RegistrationCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_case_id");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_residence_permits");

                    b.HasIndex("RegistrationCaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_residence_permits_registration_case_id");

                    b.ToTable("residence_permits", (string)null);
                });

            modelBuilder.Entity("SchaerbeekMunicipality.Domain.NationalRegister.NationalRegisterPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("BisNumber")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("bis_number");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("given_name");

                    b.Property<string>("NationalRegisterNumber")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("national_register_number");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("nationality");

                    b.HasKey("Id")
                        .HasName("pk_national_register_persons");

                    b.HasIndex("BisNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_national_register_persons_bis_number");

                    b.HasIndex("NationalRegisterNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_national_register_persons_national_register_number");

                    b.ToTable("national_register_persons", (string)null);
                });

            modelBuilder.Entity("SchaerbeekMunicipality.Domain.Notifications.OutboundNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("recipient");

                    b.Property<Guid>("RegistrationCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_case_id");

                    b.HasKey("Id")
                        .HasName("pk_outbound_notifications");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbound_notifications_created_at");

                    b.HasIndex("RegistrationCaseId")
                        .HasDatabaseName("ix_outbound_notifications_registration_case_id");

                    b.ToTable("outbound_notifications", (string)null);
                });

            modelBuilder.Entity("SchaerbeekMunicipality.Domain.Police.PoliceVerificationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("OfficerNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("officer_notes");

                    b.Property<Guid>("RegistrationCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_case_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Result")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("result");

                    b.HasKey("Id")
                        .HasName("pk_police_verification_requests");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("ix_police_verification_requests_completed_at");

                    b.HasIndex("RegistrationCaseId")
                        .HasDatabaseName("ix_police_verification_requests_registration_case_id");

                    b.ToTable("police_verification_requests", (string)null);
                });

            modelBuilder.Entity("SchaerbeekMunicipality.Domain.ReferenceData.MunicipalityReference", b =>
                {
                    b.Property<string>("PostalCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("PostalCode")
                        .HasName("pk_municipalities");

                    b.ToTable("municipalities", (string)null);
                });

            modelBuilder.Entity("SchaerbeekMunicipality.Domain.ReferenceData.StreetReference", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("postal_code");

                    b.HasKey("Id")
                        .HasName("pk_streets");

                    b.HasIndex("PostalCode")
                        .HasDatabaseName("ix_streets_postal_code");

                    b.ToTable("streets", (string)null);
                });

            modelBuilder.Entity("SchaerbeekMunicipality.Domain.Registration.CaseAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OfficerId")
                        .HasColumnType("uuid")
                        .HasColumnName("officer_id");

                    b.HasKey("Id")
                        .HasName("pk_case_audit_entries");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_case_audit_entries_case_id");

                    b.ToTable("case_audit_entries", (string)null);
                });

            modelBuilder.Entity("SchaerbeekMunicipality.Domain.Registration.RegistrationCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignedOfficerId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_officer_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("DecisionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("decision_notes");

                    b.Property<Guid?>("DecisionOfficerId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_officer_id");

                    b.Property<string>("HousingSituation")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("housing_situation");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("ResidenceCategory")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("residence_category");

                    b.Property<string>("SelectedRegisterTarget")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("register_target");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<string>("StatusBeforeSuspension")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status_before_suspension");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("suspension_reason");

                    b.Property<string>("VisitReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("visit_reason");

                    b.HasKey("Id")
                        .HasName("pk_registration_cases");

                    b.ToTable("registration_cases", (string)null);
                });

            modelBuilder.Entity("SchaerbeekMunicipality.Domain.Household.HouseholdMember", b =>
                {
                    b.HasOne("SchaerbeekMunicipality.Domain.Household.Household", null)
                        .WithMany("Members")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_household_members_households_household_id");
                });

            modelBuilder.Entity("SchaerbeekMunicipality.Domain.Identity.Person", b =>
                {
                    b.OwnsOne("SchaerbeekMunicipality.Domain.Identity.CivilStatusRecord", "CivilStatus", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly?>("MarriageDate")
                                .HasColumnType("date")
                                .HasColumnName("marriage_date");

                            b1.Property<string>("MarriagePlace")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("marriage_place");

                            b1.Property<string>("SpouseFamilyName")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("spouse_family_name");

                            b1.Property<string>("SpouseGivenName")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("spouse_given_name");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("civil_status");

                            b1.HasKey("PersonId");

                            b1.ToTable("persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_persons_persons_id");
                        });

                    b.Navigation("CivilStatus");
                });

            modelBuilder.Entity("SchaerbeekMunicipality.Domain.Registration.RegistrationCase", b =>
                {
                    b.OwnsOne("SchaerbeekMunicipality.Domain.Address.BelgianAddress", "DeclaredAddress", b1 =>
                        {
                            b1.Property<Guid>("RegistrationCaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Box")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("address_box");

                            b1.Property<string>("HouseNumber")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("address_house_number");

                            b1.Property<string>("Municipality")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("address_municipality");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("character varying(4)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("address_street");

                            b1.HasKey("RegistrationCaseId");

                            b1.ToTable("registration_cases");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationCaseId")
                                .HasConstraintName("fk_registration_cases_registration_cases_id");
                        });

                    b.OwnsOne("SchaerbeekMunicipality.Domain.Immigration.ImmigrationDecisionReference", "ImmigrationDecision", b1 =>
                        {
                            b1.Property<Guid>("RegistrationCaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("DecisionDate")
                                .HasColumnType("date")
                                .HasColumnName("immigration_decision_date");

                            b1.Property<string>("ReferenceNumber")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("immigration_decision_reference");

                            b1.HasKey("RegistrationCaseId");

                            b1.ToTable("registration_cases");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationCaseId")
                                .HasConstraintName("fk_registration_cases_registration_cases_id");
                        });

                    b.OwnsOne("SchaerbeekMunicipality.Domain.Registration.RegistrationCaseChecklist", "Checklist", b1 =>
                        {
                            b1.Property<Guid>("RegistrationCaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("AddressConfirmed")
                                .HasColumnType("boolean")
                                .HasColumnName("address_confirmed");

                            b1.Property<bool>("AddressDeclared")
                                .HasColumnType("boolean")
                                .HasColumnName("address_declared");

                            b1.Property<bool>("IdentityEstablished")
                                .HasColumnType("boolean")
                                .HasColumnName("identity_established");

                            b1.Property<bool>("LegalResidenceEstablished")
                                .HasColumnType("boolean")
                                .HasColumnName("legal_residence_established");

                            b1.Property<bool>("RegisterDeterminable")
                                .HasColumnType("boolean")
                                .HasColumnName("register_determinable");

                            b1.HasKey("RegistrationCaseId");

                            b1.ToTable("registration_cases");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationCaseId")
                                .HasConstraintName("fk_registration_cases_registration_cases_id");
                        });

                    b.Navigation("Checklist")
                        .IsRequired();

                    b.Navigation("DeclaredAddress");

                    b.Navigation("ImmigrationDecision");
                });

            modelBuilder.Entity("SchaerbeekMunicipality.Domain.Household.Household", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
