using System.Net;
using System.Text;

namespace SchaerbeekMunicipality.Infrastructure.Certificates;

public sealed class HtmlCertificateRenderer : ICertificateRenderer
{
    public string RenderResidenceCertificate(ResidenceCertificateData data)
    {
        var registeredRow = data.RegisteredAt is { } registeredAt
            ? $"<tr><th>Registered on</th><td>{registeredAt.LocalDateTime:d}</td></tr>"
            : string.Empty;

        var body = $"""
            <p class="lead">The municipality of Schaerbeek certifies that the person named below is registered at the address shown.</p>
            <table class="facts">
              <tr><th>Name</th><td>{Encode(data.PersonName)}</td></tr>
              <tr><th>National Register no.</th><td>{Encode(data.NationalRegisterNumber)}</td></tr>
              <tr><th>Address</th><td>{Encode(data.AddressLine)}</td></tr>
              <tr><th>Register</th><td>{Encode(data.RegisterTarget)}</td></tr>
              {registeredRow}
            </table>
            <p class="footer-note">This document is issued for administrative purposes only. It is generated by the Schaerbeek population department educational simulation.</p>
            """;

        return WrapDocument(
            "Attestation de résidence / Verblijfsattest",
            data.ReferenceNumber,
            data.IssuedAt,
            body);
    }

    public string RenderHouseholdComposition(HouseholdCompositionCertificateData data)
    {
        var members = new StringBuilder();
        members.Append("""
            <table class="facts members">
              <thead>
                <tr><th>Name</th><th>Role</th><th>Date of birth</th></tr>
              </thead>
              <tbody>
            """);

        foreach (var member in data.Members)
        {
            members.Append(
                $"<tr><td>{Encode(member.Name)}</td><td>{Encode(member.Role)}</td><td>{member.BirthDate:d}</td></tr>");
        }

        members.Append("""
              </tbody>
            </table>
            """);

        var body = $"""
            <p class="lead">Household composition at the declared address of the reference person.</p>
            <table class="facts">
              <tr><th>Reference person</th><td>{Encode(data.PersonName)}</td></tr>
              <tr><th>National Register no.</th><td>{Encode(data.NationalRegisterNumber)}</td></tr>
              <tr><th>Address</th><td>{Encode(data.AddressLine)}</td></tr>
            </table>
            <h2>Household members</h2>
            {members}
            <p class="footer-note">This document is issued for administrative purposes only. It is generated by the Schaerbeek population department educational simulation.</p>
            """;

        return WrapDocument(
            "Composition du ménage / Gezinssamenstelling",
            data.ReferenceNumber,
            data.IssuedAt,
            body);
    }

    private static string WrapDocument(
        string title,
        string referenceNumber,
        DateTimeOffset issuedAt,
        string bodyHtml)
    {
        var styles = """
            body { font-family: Georgia, 'Times New Roman', serif; color: #1a1a1a; margin: 2rem auto; max-width: 720px; line-height: 1.5; }
            .header { border-bottom: 2px solid #003366; padding-bottom: 1rem; margin-bottom: 1.5rem; }
            .municipality { font-size: 0.85rem; letter-spacing: 0.08em; text-transform: uppercase; color: #003366; }
            h1 { font-size: 1.35rem; margin: 0.5rem 0 0; }
            .meta { color: #555; font-size: 0.9rem; margin-top: 0.5rem; }
            .lead { font-size: 1rem; }
            table.facts { width: 100%; border-collapse: collapse; margin: 1rem 0; }
            table.facts th, table.facts td { text-align: left; padding: 0.45rem 0.6rem; border-bottom: 1px solid #ddd; vertical-align: top; }
            table.facts th { width: 38%; color: #444; font-weight: 600; }
            table.members thead th { border-bottom: 2px solid #003366; }
            h2 { font-size: 1rem; margin-top: 1.5rem; color: #003366; }
            .footer-note { margin-top: 2rem; font-size: 0.8rem; color: #666; }
            .print-actions { margin: 1rem 0 2rem; }
            @media print { .print-actions { display: none; } body { margin: 0; } }
            """;

        return $"""
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8" />
              <title>{Encode(title)} — {Encode(referenceNumber)}</title>
              <style>{styles}</style>
            </head>
            <body>
              <div class="print-actions no-print">
                <button type="button" onclick="window.print()">Print</button>
              </div>
              <header class="header">
                <div class="municipality">Commune de Schaerbeek / Gemeente Schaarbeek</div>
                <h1>{Encode(title)}</h1>
                <div class="meta">Reference {Encode(referenceNumber)} · Issued {issuedAt.LocalDateTime:g}</div>
              </header>
              <main>
                {bodyHtml}
              </main>
            </body>
            </html>
            """;
    }

    private static string Encode(string value) => WebUtility.HtmlEncode(value);
}
