using FluentValidation;
using Microsoft.Extensions.DependencyInjection;
using SchaerbeekMunicipality.Application.Auth;
using SchaerbeekMunicipality.Application.Features.BirthDeclaration;
using SchaerbeekMunicipality.Application.Features.BirthDeclaration.ClaimBirthDeclarationCase;
using SchaerbeekMunicipality.Application.Features.BirthDeclaration.ConfirmBirthDeclaration;
using SchaerbeekMunicipality.Application.Features.BirthDeclaration.GetBirthDeclarationCase;
using SchaerbeekMunicipality.Application.Features.BirthDeclaration.GetBirthDeclarationChecklist;
using SchaerbeekMunicipality.Application.Features.BirthDeclaration.LinkParent;
using SchaerbeekMunicipality.Application.Features.BirthDeclaration.ListBirthDeclarationCases;
using SchaerbeekMunicipality.Application.Features.BirthDeclaration.OpenBirthDeclarationCase;
using SchaerbeekMunicipality.Application.Features.BirthDeclaration.RecordChildDetails;
using SchaerbeekMunicipality.Application.Features.BirthDeclaration.RejectBirthDeclaration;
using SchaerbeekMunicipality.Application.Features.BirthDeclaration.ResumeBirthDeclaration;
using SchaerbeekMunicipality.Application.Features.BirthDeclaration.SetDeclarationHousehold;
using SchaerbeekMunicipality.Application.Features.BirthDeclaration.SuspendBirthDeclaration;
using SchaerbeekMunicipality.Application.Features.BirthDeclaration.UnlinkParent;
using SchaerbeekMunicipality.Application.Features.ChangeOfAddress;
using SchaerbeekMunicipality.Application.Features.ChangeOfAddress.ClaimChangeOfAddressCase;
using SchaerbeekMunicipality.Application.Features.ChangeOfAddress.ConfirmAddressChange;
using SchaerbeekMunicipality.Application.Features.ChangeOfAddress.DeclareNewAddress;
using SchaerbeekMunicipality.Application.Features.ChangeOfAddress.GetChangeOfAddressCase;
using SchaerbeekMunicipality.Application.Features.ChangeOfAddress.GetChangeOfAddressChecklist;
using SchaerbeekMunicipality.Application.Features.ChangeOfAddress.ListChangeOfAddressCases;
using SchaerbeekMunicipality.Application.Features.ChangeOfAddress.OpenChangeOfAddressCase;
using SchaerbeekMunicipality.Application.Features.ChangeOfAddress.RejectChangeOfAddress;
using SchaerbeekMunicipality.Application.Features.ChangeOfAddress.ResolveRegisteredPerson;
using SchaerbeekMunicipality.Application.Features.ChangeOfAddress.UpdateHouseholdForMove;
using SchaerbeekMunicipality.Application.Features.IdentityDocuments;
using SchaerbeekMunicipality.Application.Features.IdentityDocuments.AdvanceDocumentRequestStatus;
using SchaerbeekMunicipality.Application.Features.IdentityDocuments.AttachApplicantPhoto;
using SchaerbeekMunicipality.Application.Features.IdentityDocuments.CancelDocumentRequest;
using SchaerbeekMunicipality.Application.Features.IdentityDocuments.ClaimDocumentRequestCase;
using SchaerbeekMunicipality.Application.Features.IdentityDocuments.GetDocumentRequestCase;
using SchaerbeekMunicipality.Application.Features.IdentityDocuments.IssueDocument;
using SchaerbeekMunicipality.Application.Features.IdentityDocuments.ListDocumentRequestCases;
using SchaerbeekMunicipality.Application.Features.IdentityDocuments.OpenDocumentRequestCase;
using SchaerbeekMunicipality.Application.Features.IdentityDocuments.RecordFeePayment;
using SchaerbeekMunicipality.Application.Features.PersonFile;
using SchaerbeekMunicipality.Application.Features.PersonFile.GetPersonFile;
using SchaerbeekMunicipality.Application.Features.PersonFile.ListPersonCases;
using SchaerbeekMunicipality.Application.Features.PersonFile.SearchPersonFile;
using SchaerbeekMunicipality.Application.Features.Registration;
using SchaerbeekMunicipality.Application.Features.Registration.ApproveCase;
using SchaerbeekMunicipality.Application.Features.Registration.AttachDocument;
using SchaerbeekMunicipality.Application.Features.Registration.ClaimRegistrationCase;
using SchaerbeekMunicipality.Application.Features.Registration.ConfirmRegistration;
using SchaerbeekMunicipality.Application.Features.Registration.ConvertBisNumber;
using SchaerbeekMunicipality.Application.Features.Registration.CorrectIdentity;
using SchaerbeekMunicipality.Application.Features.Registration.DeclareAddress;
using SchaerbeekMunicipality.Application.Features.Registration.DownloadDocument;
using SchaerbeekMunicipality.Application.Features.Registration.GetCaseReviewChecklist;
using SchaerbeekMunicipality.Application.Features.Registration.GetRegistrationCase;
using SchaerbeekMunicipality.Application.Features.Registration.GetReviewDashboard;
using SchaerbeekMunicipality.Application.Features.Registration.IssueHouseholdComposition;
using SchaerbeekMunicipality.Application.Features.Registration.IssueResidenceCertificate;
using SchaerbeekMunicipality.Application.Features.Registration.LinkExistingPerson;
using SchaerbeekMunicipality.Application.Features.Registration.ListCaseAudit;
using SchaerbeekMunicipality.Application.Features.Registration.ListOutboundNotifications;
using SchaerbeekMunicipality.Application.Features.Registration.ListPendingPoliceVerifications;
using SchaerbeekMunicipality.Application.Features.Registration.ListRegistrationCases;
using SchaerbeekMunicipality.Application.Features.Registration.OpenRegistrationCase;
using SchaerbeekMunicipality.Application.Features.Registration.RecordBirthInformation;
using SchaerbeekMunicipality.Application.Features.Registration.RecordCivilStatus;
using SchaerbeekMunicipality.Application.Features.Registration.RecordHouseholdComposition;
using SchaerbeekMunicipality.Application.Features.Registration.RecordHousingSituation;
using SchaerbeekMunicipality.Application.Features.Registration.RecordIdentity;
using SchaerbeekMunicipality.Application.Features.Registration.RecordImmigrationDecision;
using SchaerbeekMunicipality.Application.Features.Registration.RecordPoliceResult;
using SchaerbeekMunicipality.Application.Features.Registration.RecordResidencePermit;
using SchaerbeekMunicipality.Application.Features.Registration.RejectCase;
using SchaerbeekMunicipality.Application.Features.Registration.ReleaseCaseLock;
using SchaerbeekMunicipality.Application.Features.Registration.RemoveDocument;
using SchaerbeekMunicipality.Application.Features.Registration.RequestPoliceVerification;
using SchaerbeekMunicipality.Application.Features.Registration.ResolveDuplicateInvestigation;
using SchaerbeekMunicipality.Application.Features.Registration.ResumeCase;
using SchaerbeekMunicipality.Application.Features.Registration.SearchNationalRegister;
using SchaerbeekMunicipality.Application.Features.Registration.SearchReferenceData;
using SchaerbeekMunicipality.Application.Features.Registration.SetResidenceCategory;
using SchaerbeekMunicipality.Application.Features.Registration.SuspendCase;
using SchaerbeekMunicipality.Application.Features.Reporting;
using SchaerbeekMunicipality.Application.Features.Reporting.GetMunicipalityReport;

namespace SchaerbeekMunicipality.Application;

public static class DependencyInjection
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        services.AddValidatorsFromAssemblyContaining<OpenRegistrationCaseValidator>();

        services.AddSingleton(TimeProvider.System);
        services.AddScoped<RegistrationCaseAuthorization>();
        services.AddScoped<RegistrationCaseGuard>();
        services.AddScoped<ICurrentOfficer, CurrentOfficer>();
        services.AddScoped<ListRegistrationCasesHandler>();
        services.AddScoped<OpenRegistrationCaseHandler>();
        services.AddScoped<GetRegistrationCaseHandler>();
        services.AddScoped<ClaimRegistrationCaseHandler>();
        services.AddScoped<ReleaseCaseLockHandler>();
        services.AddScoped<RecordIdentityHandler>();
        services.AddScoped<LinkExistingPersonHandler>();
        services.AddScoped<ConvertBisNumberHandler>();
        services.AddScoped<SearchNationalRegisterHandler>();
        services.AddScoped<CorrectIdentityHandler>();
        services.AddScoped<AttachDocumentHandler>();
        services.AddScoped<DownloadDocumentHandler>();
        services.AddScoped<RemoveDocumentHandler>();
        services.AddScoped<RegistrationResidenceEvaluator>();
        services.AddScoped<RegistrationExceptionEvaluator>();
        services.AddScoped<SetResidenceCategoryHandler>();
        services.AddScoped<RecordResidencePermitHandler>();
        services.AddScoped<RecordImmigrationDecisionHandler>();
        services.AddScoped<DeclareAddressHandler>();
        services.AddScoped<RecordHousingSituationHandler>();
        services.AddScoped<RecordHouseholdCompositionHandler>();
        services.AddScoped<RecordCivilStatusHandler>();
        services.AddScoped<RecordBirthInformationHandler>();
        services.AddScoped<ResolveDuplicateInvestigationHandler>();
        services.AddScoped<RequestPoliceVerificationHandler>();
        services.AddScoped<ListPendingPoliceVerificationsHandler>();
        services.AddScoped<RecordPoliceResultHandler>();
        services.AddScoped<GetCaseReviewChecklistHandler>();
        services.AddScoped<ApproveCaseHandler>();
        services.AddScoped<RejectCaseHandler>();
        services.AddScoped<SuspendCaseHandler>();
        services.AddScoped<ResumeCaseHandler>();
        services.AddScoped<ConfirmRegistrationHandler>();
        services.AddScoped<GetReviewDashboardHandler>();
        services.AddScoped<ListCaseAuditHandler>();
        services.AddScoped<CaseAuditRecorder>();
        services.AddScoped<IssueResidenceCertificateHandler>();
        services.AddScoped<IssueHouseholdCompositionHandler>();
        services.AddScoped<ListOutboundNotificationsHandler>();
        services.AddScoped<SearchMunicipalitiesHandler>();
        services.AddScoped<SearchStreetsHandler>();

        services.AddScoped<BirthDeclarationCaseAuthorization>();
        services.AddScoped<BirthDeclarationCaseGuard>();
        services.AddScoped<OpenBirthDeclarationCaseHandler>();
        services.AddScoped<ListBirthDeclarationCasesHandler>();
        services.AddScoped<GetBirthDeclarationCaseHandler>();
        services.AddScoped<ClaimBirthDeclarationCaseHandler>();
        services.AddScoped<Features.BirthDeclaration.ReleaseCaseLock.ReleaseCaseLockHandler>();
        services.AddScoped<RecordChildDetailsHandler>();
        services.AddScoped<LinkParentHandler>();
        services.AddScoped<UnlinkParentHandler>();
        services.AddScoped<Features.BirthDeclaration.AttachDocument.AttachDocumentHandler>();
        services.AddScoped<Features.BirthDeclaration.RemoveDocument.RemoveDocumentHandler>();
        services.AddScoped<Features.BirthDeclaration.DownloadDocument.DownloadDocumentHandler>();
        services.AddScoped<SetDeclarationHouseholdHandler>();
        services.AddScoped<GetBirthDeclarationChecklistHandler>();
        services.AddScoped<ConfirmBirthDeclarationHandler>();
        services.AddScoped<RejectBirthDeclarationHandler>();
        services.AddScoped<SuspendBirthDeclarationHandler>();
        services.AddScoped<ResumeBirthDeclarationHandler>();

        services.AddScoped<ChangeOfAddressCaseAuthorization>();
        services.AddScoped<ChangeOfAddressCaseGuard>();
        services.AddScoped<OpenChangeOfAddressCaseHandler>();
        services.AddScoped<ListChangeOfAddressCasesHandler>();
        services.AddScoped<GetChangeOfAddressCaseHandler>();
        services.AddScoped<ClaimChangeOfAddressCaseHandler>();
        services.AddScoped<Features.ChangeOfAddress.ReleaseCaseLock.ReleaseCaseLockHandler>();
        services.AddScoped<DeclareNewAddressHandler>();
        services.AddScoped<UpdateHouseholdForMoveHandler>();
        services.AddScoped<UnlinkHouseholdMemberHandler>();
        services.AddScoped<Features.ChangeOfAddress.RequestPoliceVerification.RequestPoliceVerificationHandler>();
        services.AddScoped<Features.ChangeOfAddress.AttachDocument.AttachDocumentHandler>();
        services.AddScoped<Features.ChangeOfAddress.RemoveDocument.RemoveDocumentHandler>();
        services.AddScoped<Features.ChangeOfAddress.DownloadDocument.DownloadDocumentHandler>();
        services.AddScoped<GetChangeOfAddressChecklistHandler>();
        services.AddScoped<ConfirmAddressChangeHandler>();
        services.AddScoped<RejectChangeOfAddressHandler>();
        services.AddScoped<ResolveRegisteredPersonHandler>();

        services.AddScoped<DocumentRequestCaseAuthorization>();
        services.AddScoped<DocumentRequestCaseGuard>();
        services.AddScoped<ReportingAuthorization>();
        services.AddScoped<GetMunicipalityReportHandler>();
        services.AddScoped<PersonFileAuthorization>();
        services.AddScoped<GetPersonFileHandler>();
        services.AddScoped<SearchPersonFileHandler>();
        services.AddScoped<ListPersonCasesHandler>();
        services.AddScoped<OpenDocumentRequestCaseHandler>();
        services.AddScoped<ListDocumentRequestCasesHandler>();
        services.AddScoped<GetDocumentRequestCaseHandler>();
        services.AddScoped<ClaimDocumentRequestCaseHandler>();
        services.AddScoped<Features.IdentityDocuments.ReleaseCaseLock.ReleaseCaseLockHandler>();
        services.AddScoped<AttachApplicantPhotoHandler>();
        services.AddScoped<Features.IdentityDocuments.RemoveDocument.RemoveDocumentHandler>();
        services.AddScoped<Features.IdentityDocuments.DownloadDocument.DownloadDocumentHandler>();
        services.AddScoped<RecordFeePaymentHandler>();
        services.AddScoped<AdvanceDocumentRequestStatusHandler>();
        services.AddScoped<IssueDocumentHandler>();
        services.AddScoped<CancelDocumentRequestHandler>();
        services.AddScoped<Features.IdentityDocuments.ResolveRegisteredPerson.ResolveRegisteredPersonHandler>();

        return services;
    }
}